name: wps

on: push
  # pull_request:
  #   branches:
  #     - main
 
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: wemake-services/wemake-python-styleguide@master
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}